<a href="https://colab.research.google.com/github/udghosh/Employee_Attrition/blob/main/ANN_job_role_match_poor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sys


from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn import datasets
from sklearn.metrics import accuracy_score

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pydot
import graphviz
from IPython.display import SVG 
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving job_role_Final(test)clust.csv to job_role_Final(test)clust (1).csv


In [ ]:
df = pd.read_csv('job_role_Final(test)clust (1).csv', encoding= 'unicode_escape')
df.head()

Job_Roles Skills_1 Skills_2  ... Skills_21 Skills_22 Skills_23
0  .NET DEVELOPER     .Net     java  ...       NaN       NaN       NaN
1  .NET DEVELOPER     .Net      C++  ...       NaN       NaN       NaN
2  .NET DEVELOPER   VISUAL       C#  ...       NaN       NaN       NaN
3  .NET DEVELOPER       C#      C++  ...       NaN       NaN       NaN
4  .NET DEVELOPER  ECLIPSE     JAVA  ...       NaN       NaN       NaN

[5 rows x 24 columns]

In [ ]:
df.isna().sum()

Job_Roles       0
Skills_1       50
Skills_2        1
Skills_3        8
Skills_4      107
Skills_5      351
Skills_6     1282
Skills_7     1810
Skills_8     2139
Skills_9     2379
Skills_10    2625
Skills_11    2803
Skills_12    2931
Skills_13    3013
Skills_14    3092
Skills_15    3154
Skills_16    3216
Skills_17    3247
Skills_18    3274
Skills_19    3306
Skills_20    3321
Skills_21    3327
Skills_22    3334
Skills_23    3334
dtype: int64

In [ ]:
df = df.drop(['Skills_6',	'Skills_7',	'Skills_8','Skills_8',	'Skills_9',	'Skills_10',	'Skills_11',	'Skills_12','Skills_13',	'Skills_14',	'Skills_15',	'Skills_16',	'Skills_17',	'Skills_18',	'Skills_19',	'Skills_20',	'Skills_21',	'Skills_22',	'Skills_23'],axis=1)

In [ ]:
df.head()

Job_Roles Skills_1 Skills_2    Skills_3 Skills_4 Skills_5
0  .NET DEVELOPER     .Net     java         c++      NaN      NaN
1  .NET DEVELOPER     .Net      C++    DATABASE     HTML     HTML
2  .NET DEVELOPER   VISUAL       C#         C++      NaN      NaN
3  .NET DEVELOPER       C#      C++  JAVASCRIPT     JAVA      NaN
4  .NET DEVELOPER  ECLIPSE     JAVA      jQuery       C#      C++

In [ ]:
df.apply(lambda x: x.astype(str).str.upper())


Job_Roles    Skills_1 Skills_2    Skills_3    Skills_4 Skills_5
0     .NET DEVELOPER        .NET     JAVA         C++         NAN      NAN
1     .NET DEVELOPER        .NET      C++    DATABASE        HTML     HTML
2     .NET DEVELOPER      VISUAL       C#         C++         NAN      NAN
3     .NET DEVELOPER          C#      C++  JAVASCRIPT        JAVA      NAN
4     .NET DEVELOPER     ECLIPSE     JAVA      JQUERY          C#      C++
...              ...         ...      ...         ...         ...      ...
3332   WEB DEVELOPER         C++   DJANGO        HTML  JAVASCRIPT   PYTHON
3333   WEB DEVELOPER         C++     HTML  JAVASCRIPT        JSON      PHP
3334   WEB DEVELOPER         CSS     HTML       LINUX      VISUAL  ANGULAR
3335   WEB DEVELOPER        HTML      CSS         PHP  JAVASCRIPT      NAN
3336   WEB DEVELOPER  JAVASCRIPT     HTML         XML       JIIRA    LINUX

[3337 rows x 6 columns]

In [ ]:
df.dropna(subset = ["Skills_1","Skills_2","Skills_3","Skills_4","Skills_5"], inplace=True)

In [ ]:
df.isna().sum()

Job_Roles    0
Skills_1     0
Skills_2     0
Skills_3     0
Skills_4     0
Skills_5     0
dtype: int64

In [ ]:
df.head()

Job_Roles Skills_1     Skills_2  Skills_3 Skills_4  Skills_5
1  .NET DEVELOPER     .Net          C++  DATABASE     HTML      HTML
4  .NET DEVELOPER  ECLIPSE         JAVA    jQuery       C#       C++
5  .NET DEVELOPER      WEB  Development         C      C++      Java
7  .NET DEVELOPER     Java           js      .NET   Oracle     Mysql
8  .NET DEVELOPER  ECLIPSE         JAVA        C#      C++  DATABASE

In [ ]:
df.shape[0]


2938

In [ ]:
 df.Job_Roles.nunique()

19

In [ ]:
df['Job_Roles'].unique().tolist()

['.NET DEVELOPER',
 'ANDROID DEVELOPER',
 'BACKEND DEVELOPER',
 'CLOUD DEVELOPER',
 'COMMUNICATION ENGINEER',
 'DATA ANALYST',
 'DATABASE DESIGNER',
 'DEVELOPER',
 'FRONTEND DEVELOPER',
 'FULLSTACK DEVELOPER',
 'IOS DEVELOPER',
 'IOT DEVELOPER',
 'JAVA DEVELOPER',
 'ML DEVELOPER',
 'PHP DEVELOPER',
 'PYTHON DEVELOPER',
 'SOFTWARE DEVELOPER',
 'UI DEVELOPER',
 'WEB DEVELOPER']

In [ ]:
#df = df.replace(to_replace = np.nan, value ='0') 
#df

In [ ]:
#transform non-numerical into numerical
from sklearn.preprocessing import LabelEncoder

for column in df.columns:
    if df[column].dtype == np.float:
      continue
    df[column] = LabelEncoder().fit_transform(df[column])

In [ ]:
df

Job_Roles  Skills_1  Skills_2  Skills_3  Skills_4  Skills_5
1             0         0        49        84       133       142
4             0       114       150       390        55        56
5             0       274       109        48        56       174
7             0       153       349         1       250       234
8             0       114       150        49        56        85
...         ...       ...       ...       ...       ...       ...
3331         18       272        49       146       362        56
3332         18        62        96       146       153       277
3333         18        62       134       164       165       267
3334         18        74       134       197       362        34
3336         18       157       134       355       159       200

[2938 rows x 6 columns]

In [ ]:
y=df["Job_Roles"]
X=df.drop("Job_Roles",axis=1)

In [ ]:
X.head()

Skills_1  Skills_2  Skills_3  Skills_4  Skills_5
1         0        49        84       133       142
4       114       150       390        55        56
5       274       109        48        56       174
7       153       349         1       250       234
8       114       150        49        56        85

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.10,random_state=0)

In [ ]:
y_test = y_test.to_numpy()
y_train = y_train.to_numpy()
X_train = X_train.to_numpy()
X_test = X_test.to_numpy()

In [ ]:
y_test

array([ 8, 14,  7, 18, 18, 18, 12,  8, 17, 12, 12,  6,  7,  0,  2, 13, 18,
        2, 12, 12, 13, 14,  0, 16, 17, 18, 14,  2,  6,  6, 14, 18, 18, 18,
       14,  9,  1,  1, 15,  9, 18, 18,  8, 12, 13,  7, 13, 15, 10, 15,  1,
        9, 12, 11,  9,  8, 16, 16,  6, 14, 12, 15, 15, 18,  8,  9, 14, 12,
       16,  0, 15, 12, 12, 18,  6, 14,  1,  8, 14, 16,  8, 16, 16, 18, 15,
       16, 11,  6, 16,  7,  0,  9,  5, 18, 15,  9, 16,  9,  2, 14, 13, 18,
       15, 15,  8, 14,  0, 11, 14, 18, 14, 18,  1,  7, 16,  1, 12, 16, 18,
       16, 18,  6, 14, 15,  6,  2, 12,  1,  2, 14, 14, 16, 18, 18,  9,  6,
       12, 18,  9, 18,  1, 15, 10, 15, 14, 18, 12,  2,  7, 12,  1,  2,  6,
       14, 12,  1, 14, 13, 16,  1,  6,  8, 10, 16,  7,  7, 12, 12,  2, 12,
       14, 16, 12, 14,  7,  7, 16,  0, 17, 18, 16, 17,  2, 14, 13, 16,  7,
       16, 18, 12, 13, 16, 18,  0, 15, 18,  2,  0,  8, 16,  6, 18, 12, 14,
        1, 16,  6,  6, 14, 16, 18, 15,  7,  6, 12,  8, 18, 13, 14, 10, 18,
       12,  6,  1, 16,  2

In [ ]:
X_test

array([[132, 166,  82, 174, 197],
       [214, 381, 226, 413,  73],
       [ 87, 280,  88, 152, 141],
       ...,
       [249,  59,  62, 330,  73],
       [144,  83, 217,  56, 142],
       [ 87,  15, 268, 210, 456]])

In [ ]:
'''
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

X_train.mean()
'''

'\nfrom sklearn.preprocessing import StandardScaler\nsc = StandardScaler()\nX_train=sc.fit_transform(X_train)\nX_test=sc.fit_transform(X_test)\n\nX_train.mean()\n'

In [ ]:
model = Sequential()

model.add(Dense(19,input_shape = (5,),activation='relu'))
model.add(Dense(19,activation='relu'))
model.add(Dense(19,activation='relu'))
model.add(Dense(19,activation='relu'))
model.add(Dense(19,activation='relu'))
model.add(Dense(19,activation='relu'))
model.add(Dense(19,activation='relu'))
model.add(Dense(1,activation='softmax'))

In [ ]:
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])


In [ ]:
X_train

array([[214, 140, 375, 420, 447],
       [ 59,  49, 146, 262, 384],
       [157, 130, 257,  70, 214],
       ...,
       [132, 230, 204, 183, 277],
       [ 10, 279,  51,  70, 142],
       [ 62, 279, 217, 242, 146]])

In [ ]:

model.fit(X_train, y_train, batch_size = 100, epochs = 100)

Epoch 1/100
27/27 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.0517
Epoch 2/100
27/27 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.0576
Epoch 3/100
27/27 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.0591
Epoch 4/100
27/27 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.0529
Epoch 5/100
27/27 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.0590
Epoch 6/100
27/27 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.0564
Epoch 7/100
27/27 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.0496
Epoch 8/100
27/27 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.0628
Epoch 9/100
27/27 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.0520
Epoch 10/100
27/27 [==============================] - 0s 1ms/step - loss:

In [ ]:
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_75 (Dense)             (None, 19)                114       
_________________________________________________________________
dense_76 (Dense)             (None, 19)                380       
_________________________________________________________________
dense_77 (Dense)             (None, 19)                380       
_________________________________________________________________
dense_78 (Dense)             (None, 19)                380       
_________________________________________________________________
dense_79 (Dense)             (None, 19)                380       
_________________________________________________________________
dense_80 (Dense)             (None, 19)                380       
_________________________________________________________________
dense_81 (Dense)             (None, 19)              

In [ ]:
y_pred = model.predict(X_test)
#y_test_class = np.argmax(y_test)
#y_pred_class = np.argmax(y_pred)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           1       0.06      1.00      0.12        18
           2       0.00      0.00      0.00        12
           5       0.00      0.00      0.00         3
           6       0.00      0.00      0.00        21
           7       0.00      0.00      0.00        19
           8       0.00      0.00      0.00        20
           9       0.00      0.00      0.00        15
          10       0.00      0.00      0.00         5
          11       0.00      0.00      0.00         5
          12       0.00      0.00      0.00        34
          13       0.00      0.00      0.00         9
          14       0.00      0.00      0.00        31
          15       0.00      0.00      0.00        17
          16       0.00      0.00      0.00        29
          17       0.00      0.00      0.00         5
          18       0.00      0.00      0.00        40

    accuracy              

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

TN = cm[0][0]
TP = cm[1][1]
FN = cm[1][0]
FP = cm[0][1]

print(cm)
print('Model Accuracy = {}'.format((TN+TP) / (TP+TN+FN+FP)))

[[ 0 11  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 34  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 31  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 29  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 40  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
Model Accuracy = 0.6206896551724138


In [ ]:
#from sklearn.linear_model import LogisticRegression
#from sklearn.tree import DecisionTreeClassifier
#from sklearn.ensemble import RandomForestClassifier
#from sklearn.neighbors import KNeighborsClassifier
#from sklearn.svm import SVC
#from sklearn.naive_bayes import GaussianNB

In [ ]:
#lr=LogisticRegression()
#dt=DecisionTreeClassifier()
#rm=RandomForestClassifier()
#supvm=SVC()
#knn=KNeighborsClassifier(n_neighbors=5)
#gnb=GaussianNB()

In [ ]:
#for a,b in zip([lr,dt,rm,supvm,knn,gnb],["Logistic Regression","Decision Tree","Random Forest","Support Vector Machine","K Nearest Neighbours","Naive Bayes"]):
 #   a.fit(X_train,y_train)
  #  prediction=a.predict(X_train)
   # y_pred=a.predict(X_test)
   # score1=accuracy_score(y_train,prediction)
   # score=accuracy_score(y_test,y_pred)
   # msg1="[%s] training data accuracy is : %f" % (b,score1)
   # msg2="[%s] test data accuracy is : %f" % (b,score)
   # print(msg1)
   # print(msg2)